python filterPeakWindowsLineNums.py ../DNasePeaks/allPeaksWindowsO15D282M652FiltLCL ../DNasePeaks/HumanUpFibroblastLines ../DNaseRegionData/HumanUpFibroblast 0
./liftOver -minMatch=0.8 ../DNaseRegionData/HumanUpFibroblast ../LiftoverChains/hg19ToPanTro2.over.chain ../DNaseRegionData/HumanUpFibroblastpanTro2 ../DNaseRegionData/HumanUpFibroblastUnmapped
subtractBed -a ../DNaseRegionData/HumanUpFibroblast -b ../DNaseRegionData/HumanUpFibroblastUnmapped > ../DNaseRegionData/HumanUpFibroblastMappanTro2
./liftOver -minMatch=0.8 ../DNaseRegionData/HumanUpFibroblast ../LiftoverChains/hg19ToRheMac2.over.chain ../DNaseRegionData/HumanUpFibroblastrheMac2 ../DNaseRegionData/HumanUpFibroblastUnmappedrheMac2
subtractBed -a ../DNaseRegionData/HumanUpFibroblastMappanTro2 -b ../DNaseRegionData/HumanUpFibroblastUnmappedrheMac2 > ../DNaseRegionData/HumanUpFibroblastMappanTro2rheMac2
sort -u -k1,1 -k2,2n -k3,3n ../DNaseRegionData/HumanUpFibroblastMappanTro2rheMac2 > ../DNaseRegionData/HumanUpFibroblastMappanTro2rheMac2Sorted
python getRegionsOfInterest.py ../DNaseRegionData/HumanUpFibroblastMappanTro2rheMac2Sorted 0 1 2 100 1 0 0 1 0 0 ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../AlignmentFiles/all.hg19.panTro2.rheMac2.substitutions > ../DNaseRegionData/HumanUpFibroblastSubstitutionsCommon100bp
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../AlignmentFiles/all.hg19.panTro2.rheMac2.insertions > ../DNaseRegionData/HumanUpFibroblastInsertions100bp
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../AlignmentFiles/all.hg19.panTro2.rheMac2.deletions > ../DNaseRegionData/HumanUpFibroblastDeletions100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanUpFibroblastSubstitutionsCommon100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSubstitutions100bp -1 0 1 2 ../DNaseRegionData/HumanUpFibroblastSubstitutionsSingle100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanUpFibroblastInsertions100bp ../DNaseRegionData/HumanUpFibroblastRegionsToInsertions100bp -1 0 1 2 ../DNaseRegionData/HumanUpFibroblastInsertionsSingle100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanUpFibroblastDeletions100bp ../DNaseRegionData/HumanUpFibroblastRegionsToDeletions100bp -1 0 1 2 ../DNaseRegionData/HumanUpFibroblastDeletionsSingle100bp
cat ../DNaseRegionData/HumanUpFibroblastSubstitutionsCommon100bp ../DNaseRegionData/HumanUpFibroblastInsertions100bp ../DNaseRegionData/HumanUpFibroblastDeletions100bp > ../DNaseRegionData/HumanUpFibroblastSeqDiffs100bp
sort -k1,1 -k2,2n -k3,3n ../DNaseRegionData/HumanUpFibroblastSeqDiffs100bp > ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp -1 0 1 2 ../DNaseRegionData/HumanUpFibroblastSeqDiffsSingle100bp
python addNamesToBed.py ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanUpFibroblastMapRegionSorted4Col100bp

python getRegionsOfInterest.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp 0 1 2 10 1 0 0 1 0 0 ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsSortedRegion10bp
python getRegionsOfInterest.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp 0 1 2 100 1 0 0 1 0 0 ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsSortedRegion100bp
python getRegionsOfInterest.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp 0 1 2 1000 1 0 0 1 0 0 ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsSortedRegion1000bp
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservP ../DNaseRegionData/HumanUpFibroblastMapConservP100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservPNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservP10bp ../DNaseRegionData/HumanUpFibroblastMapConservP100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservP10bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservP100bp ../DNaseRegionData/HumanUpFibroblastMapConservP100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservP100bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservP1000bp ../DNaseRegionData/HumanUpFibroblastMapConservP100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservP1000bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservM ../DNaseRegionData/HumanUpFibroblastMapConservM100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservMNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservM10bp ../DNaseRegionData/HumanUpFibroblastMapConservM100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservM10bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservM100bp ../DNaseRegionData/HumanUpFibroblastMapConservM100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservM100bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservM1000bp ../DNaseRegionData/HumanUpFibroblastMapConservM100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanUpFibroblastSeqDiffsConservM1000bpNorm

python getDistancesFeaturesNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp 100 ../DNaseRegionData/SeqDiffDistances100bp/HumanUpFibroblastDistFeatsNorm

python getRegionsOfInterest.py ../DNaseRegionData/HumanUpFibroblastMappanTro2rheMac2Sorted 0 1 2 100000 1 0 0 1 0 0 ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100kb
python addNamesToBed.py ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100kb ../DNaseRegionData/HumanUpFibroblastMapRegionSorted4Col100kb
python getSubstitutionFastasAllSubs.py ../AlignmentFiles/all.hg19.panTro2.rheMac2.substitutions ../DNaseRegionData/HumanUpFibroblastSubstitutionsCommon100bp ../DNaseRegionData/HumanUpFibroblastSubstitutionsToSequences100bp
python substituteFastas.py ../DNaseRegionData/HumanUpFibroblastSubstitutionsToSequences100bp ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastMapFastasSorted100bp ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastFastasSubstitutionsSub100bp
python removeInsertions.py ../DNaseRegionData/HumanUpFibroblastInsertions100bp ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastMapFastasSorted100bp ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastFastasInsertionsRemoved100bp
python getSubstitutionFastasAllSubs.py ../AlignmentFiles/all.hg19.panTro2.rheMac2.deletions ../DNaseRegionData/HumanUpFibroblastDeletions100bp ../DNaseRegionData/HumanUpFibroblastDeletionsToSequences100bp
python addDeletions.py ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastMapFastasSorted100bp ../DNaseRegionData/HumanUpFibroblastDeletionsToSequences100bp ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastFastasDeletionsAdded100bp
python makeFIMOScript.py ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastMapFastasSorted100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/HumanUpFDR1GCContent100kb runFIMOHumanUpFibroblast100kb.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundHumanUpFibroblast/FIMOHumanUpFibroblast100kb /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All
python makeFIMOScriptSub.py ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastFastasSubstitutionsSub100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/HumanUpFDR1GCContent100kb runFIMOHumanUpFibroblast100kbS.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundHumanUpFibroblastSub/FIMOHumanUpFibroblast100kbSub /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp
python makeFIMOScriptSub.py ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastFastasInsertionsRemoved100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/HumanUpFDR1GCContent100kb runFIMOHumanUpFibroblast100kbI.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundHumanUpFibroblastIns/FIMOHumanUpFibroblast100kbIns /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp
python makeFIMOScriptSub.py ../DNaseRegionData/DNaseFastas100bp/HumanUpFibroblastFastasDeletionsAdded100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/HumanUpFDR1GCContent100kb runFIMOHumanUpFibroblast100kbD.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundHumanUpFibroblastDel/FIMOHumanUpFibroblast100kbDel /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp

cat ../PWMData/HumanUpFibroblastSubFeatures100bp ../PWMData/HumanUpFibroblastInsertFeatures100bp ../PWMData/HumanUpFibroblastDelFeatures100bp > ../PWMData/HumanUpFibroblastSeqDiffFUnsorted100bp
cat ../PWMData/HumanUpFibroblastSubFeaturesUp100bp ../PWMData/HumanUpFibroblastInsertFeaturesUp100bp ../PWMData/HumanUpFibroblastDelFeaturesUp100bp > ../PWMData/HumanUpFibroblastSeqDiffFUnsortedUp100bp
cat ../PWMData/HumanUpFibroblastSubFeaturesDown100bp ../PWMData/HumanUpFibroblastInsertFeaturesDown100bp ../PWMData/HumanUpFibroblastDelFeaturesDown100bp > ../PWMData/HumanUpFibroblastSeqDiffFUnsortedDown100bp
cat ../PWMData/HumanUpFibroblastSub100kbFeatures100bp ../PWMData/HumanUpFibroblastInsert100kbFeatures100bp ../PWMData/HumanUpFibroblastDel100kbFeatures100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFUnsorted100bp
cat ../PWMData/HumanUpFibroblastSub100kbFeaturesUp100bp ../PWMData/HumanUpFibroblastInsert100kbFeaturesUp100bp ../PWMData/HumanUpFibroblastDel100kbFeaturesUp100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFUnsortedUp100bp
cat ../PWMData/HumanUpFibroblastSub100kbFeaturesDown100bp ../PWMData/HumanUpFibroblastInsert100kbFeaturesDown100bp ../PWMData/HumanUpFibroblastDel100kbFeaturesDown100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFUnsortedDown100bp
paste ../DNaseRegionData/HumanUpFibroblastSeqDiffs100bp ../PWMData/HumanUpFibroblastSeqDiffFUnsorted100bp > ../PWMData/HumanUpFibroblastSeqDiffFULoc100bp
paste ../DNaseRegionData/HumanUpFibroblastSeqDiffs100bp ../PWMData/HumanUpFibroblastSeqDiffFUnsortedUp100bp > ../PWMData/HumanUpFibroblastSeqDiffFULocUp100bp
paste ../DNaseRegionData/HumanUpFibroblastSeqDiffs100bp ../PWMData/HumanUpFibroblastSeqDiffFUnsortedDown100bp > ../PWMData/HumanUpFibroblastSeqDiffFULocDown100bp
paste ../DNaseRegionData/HumanUpFibroblastSeqDiffs100bp ../PWMData/HumanUpFibroblastSeqDiff100kbFUnsorted100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFULoc100bp
paste ../DNaseRegionData/HumanUpFibroblastSeqDiffs100bp ../PWMData/HumanUpFibroblastSeqDiff100kbFUnsortedUp100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFULocUp100bp
paste ../DNaseRegionData/HumanUpFibroblastSeqDiffs100bp ../PWMData/HumanUpFibroblastSeqDiff100kbFUnsortedDown100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFULocDown100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanUpFibroblastSeqDiffFULoc100bp > ../PWMData/HumanUpFibroblastSeqDiffFSLoc100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanUpFibroblastSeqDiffFULocUp100bp > ../PWMData/HumanUpFibroblastSeqDiffFSLocUp100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanUpFibroblastSeqDiffFULocDown100bp > ../PWMData/HumanUpFibroblastSeqDiffFSLocDown100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanUpFibroblastSeqDiff100kbFULoc100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFSLoc100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanUpFibroblastSeqDiff100kbFULocUp100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFSLocUp100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanUpFibroblastSeqDiff100kbFULocDown100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFSLocDown100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanUpFibroblastSeqDiffFSLoc100bp > ../PWMData/HumanUpFibroblastSeqDiffFSorted100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanUpFibroblastSeqDiffFSLocUp100bp > ../PWMData/HumanUpFibroblastSeqDiffFSortedUp100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanUpFibroblastSeqDiffFSLocDown100bp > ../PWMData/HumanUpFibroblastSeqDiffFSortedDown100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanUpFibroblastSeqDiff100kbFSLoc100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFSorted100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanUpFibroblastSeqDiff100kbFSLocUp100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFSortedUp100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanUpFibroblastSeqDiff100kbFSLocDown100bp > ../PWMData/HumanUpFibroblastSeqDiff100kbFSortedDown100bp

intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadCtcfStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToCtcfReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K4me3ReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K27me3ReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K36me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K36me3ReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadEzh2StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToEzh2ReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me1StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K4me1ReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9acStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K9acReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K9me3ReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27acStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K27acReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K79me2StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K79me2ReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH4K20me1StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH4K20me1ReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH2azStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH2azReadNums
intersectBed -a ../DNaseRegionData/HumanUpFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me2StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K4me2ReadNums

python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadCtcfStdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToCtcfReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToCtcf 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me3StdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K4me3ReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH3K4me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27me3StdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K27me3ReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH3K27me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K36me3StdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K36me3ReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH3K36me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadEzh2StdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToEzh2ReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToEzh2 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me1StdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K4me1ReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH3K4me1 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9acStdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K9acReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH3K9ac 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9me3StdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K9me3ReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH3K9me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27acStdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K27acReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH3K27ac 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K79me2StdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K79me2ReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH3K79me2 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH4K20me1StdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH4K20me1ReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH4K20me1 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH2azStdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH2azReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH2az 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me2StdPk.Sorted.broadPeak ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanUpFibroblastRegion100bpToH3K4me2ReadNums ../ENCODEData/NHDF_Ad/HumanUpFibroblastSeqDiffsToH3K4me2 3 3
python combineFeatureFiles.py ../DNaseRegionData/HumanUpFibroblastSeqDiffsSorted100bp ../FeatureData/HumanUpFibroblastFeatureFileNamesUp ../FeatureData/HumanUpFibroblastFeaturesUp100bp
python associateRegionsToClusters.py ../DNaseRegionData/HumanUpFibroblastMappanTro2rheMac2Sorted ../HumanGenome/HumanCoordsClustersFileNames ../DNaseRegionData/HumanUpFibroblastMapClusters 4
python associateSeqDiffsToClusters.py ../DNaseRegionData/HumanUpFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/HumanUpFibroblastMapClusters ../DNaseRegionData/HumanUpFibroblastSeqDiffsClusters100bp


python filterPeakWindowsLineNums.py ../DNasePeaks/allPeaksWindowsO15D282M652FiltLCL ../DNasePeaks/HumanDownFibroblastLines ../DNaseRegionData/HumanDownFibroblast 0
./liftOver -minMatch=0.8 ../DNaseRegionData/HumanDownFibroblast ../LiftoverChains/hg19ToPanTro2.over.chain ../DNaseRegionData/HumanDownFibroblastpanTro2 ../DNaseRegionData/HumanDownFibroblastUnmapped
subtractBed -a ../DNaseRegionData/HumanDownFibroblast -b ../DNaseRegionData/HumanDownFibroblastUnmapped > ../DNaseRegionData/HumanDownFibroblastMappanTro2
./liftOver -minMatch=0.8 ../DNaseRegionData/HumanDownFibroblast ../LiftoverChains/hg19ToRheMac2.over.chain ../DNaseRegionData/HumanDownFibroblastrheMac2 ../DNaseRegionData/HumanDownFibroblastUnmappedrheMac2
subtractBed -a ../DNaseRegionData/HumanDownFibroblastMappanTro2 -b ../DNaseRegionData/HumanDownFibroblastUnmappedrheMac2 > ../DNaseRegionData/HumanDownFibroblastMappanTro2rheMac2
sort -u -k1,1 -k2,2n -k3,3n ../DNaseRegionData/HumanDownFibroblastMappanTro2rheMac2 > ../DNaseRegionData/HumanDownFibroblastMappanTro2rheMac2Sorted
python getRegionsOfInterest.py ../DNaseRegionData/HumanDownFibroblastMappanTro2rheMac2Sorted 0 1 2 100 1 0 0 1 0 0 ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../AlignmentFiles/all.hg19.panTro2.rheMac2.substitutions > ../DNaseRegionData/HumanDownFibroblastSubstitutionsCommon100bp
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../AlignmentFiles/all.hg19.panTro2.rheMac2.insertions > ../DNaseRegionData/HumanDownFibroblastInsertions100bp
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../AlignmentFiles/all.hg19.panTro2.rheMac2.deletions > ../DNaseRegionData/HumanDownFibroblastDeletions100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanDownFibroblastSubstitutionsCommon100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSubstitutions100bp -1 0 1 2 ../DNaseRegionData/HumanDownFibroblastSubstitutionsSingle100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanDownFibroblastInsertions100bp ../DNaseRegionData/HumanDownFibroblastRegionsToInsertions100bp -1 0 1 2 ../DNaseRegionData/HumanDownFibroblastInsertionsSingle100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanDownFibroblastDeletions100bp ../DNaseRegionData/HumanDownFibroblastRegionsToDeletions100bp -1 0 1 2 ../DNaseRegionData/HumanDownFibroblastDeletionsSingle100bp
cat ../DNaseRegionData/HumanDownFibroblastSubstitutionsCommon100bp ../DNaseRegionData/HumanDownFibroblastInsertions100bp ../DNaseRegionData/HumanDownFibroblastDeletions100bp > ../DNaseRegionData/HumanDownFibroblastSeqDiffs100bp
sort -k1,1 -k2,2n -k3,3n ../DNaseRegionData/HumanDownFibroblastSeqDiffs100bp > ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp -1 0 1 2 ../DNaseRegionData/HumanDownFibroblastSeqDiffsSingle100bp
python addNamesToBed.py ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp ../DNaseRegionData/HumanDownFibroblastMapRegionSorted4Col100bp

python getRegionsOfInterest.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp 0 1 2 10 1 0 0 1 0 0 ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsSortedRegion10bp
python getRegionsOfInterest.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp 0 1 2 100 1 0 0 1 0 0 ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsSortedRegion100bp
python getRegionsOfInterest.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp 0 1 2 1000 1 0 0 1 0 0 ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsSortedRegion1000bp
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservP ../DNaseRegionData/HumanDownFibroblastMapConservP100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservPNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservP10bp ../DNaseRegionData/HumanDownFibroblastMapConservP100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservP10bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservP100bp ../DNaseRegionData/HumanDownFibroblastMapConservP100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservP100bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservP1000bp ../DNaseRegionData/HumanDownFibroblastMapConservP100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservP1000bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservM ../DNaseRegionData/HumanDownFibroblastMapConservM100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservMNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservM10bp ../DNaseRegionData/HumanDownFibroblastMapConservM100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservM10bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservM100bp ../DNaseRegionData/HumanDownFibroblastMapConservM100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservM100bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservM1000bp ../DNaseRegionData/HumanDownFibroblastMapConservM100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/HumanDownFibroblastSeqDiffsConservM1000bpNorm

python getDistancesFeaturesNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp 100 ../DNaseRegionData/SeqDiffDistances100bp/HumanDownFibroblastDistFeatsNorm

python getRegionsOfInterest.py ../DNaseRegionData/HumanDownFibroblastMappanTro2rheMac2Sorted 0 1 2 100000 1 0 0 1 0 0 ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100kb
python addNamesToBed.py ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100kb ../DNaseRegionData/HumanDownFibroblastMapRegionSorted4Col100kb
python getSubstitutionFastasAllSubs.py ../AlignmentFiles/all.hg19.panTro2.rheMac2.substitutions ../DNaseRegionData/HumanDownFibroblastSubstitutionsCommon100bp ../DNaseRegionData/HumanDownFibroblastSubstitutionsToSequences100bp
python substituteFastas.py ../DNaseRegionData/HumanDownFibroblastSubstitutionsToSequences100bp ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastMapFastasSorted100bp ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastFastasSubstitutionsSub100bp
python removeInsertions.py ../DNaseRegionData/HumanDownFibroblastInsertions100bp ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastMapFastasSorted100bp ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastFastasInsertionsRemoved100bp
python getSubstitutionFastasAllSubs.py ../AlignmentFiles/all.hg19.panTro2.rheMac2.deletions ../DNaseRegionData/HumanDownFibroblastDeletions100bp ../DNaseRegionData/HumanDownFibroblastDeletionsToSequences100bp
python addDeletions.py ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastMapFastasSorted100bp ../DNaseRegionData/HumanDownFibroblastDeletionsToSequences100bp ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastFastasDeletionsAdded100bp
python makeFIMOScript.py ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastMapFastasSorted100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/HumanDownFDR1GCContent100kb runFIMOHumanDownFibroblast100kb.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundHumanDownFibroblast/FIMOHumanDownFibroblast100kb /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All
python makeFIMOScriptSub.py ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastFastasSubstitutionsSub100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/HumanDownFDR1GCContent100kb runFIMOHumanDownFibroblast100kbS.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundHumanDownFibroblastSub/FIMOHumanDownFibroblast100kbSub /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp
python makeFIMOScriptSub.py ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastFastasInsertionsRemoved100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/HumanDownFDR1GCContent100kb runFIMOHumanDownFibroblast100kbI.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundHumanDownFibroblastIns/FIMOHumanDownFibroblast100kbIns /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp
python makeFIMOScriptSub.py ../DNaseRegionData/DNaseFastas100bp/HumanDownFibroblastFastasDeletionsAdded100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/HumanDownFDR1GCContent100kb runFIMOHumanDownFibroblast100kbD.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundHumanDownFibroblastDel/FIMOHumanDownFibroblast100kbDel /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp

cat ../PWMData/HumanDownFibroblastSubFeatures100bp ../PWMData/HumanDownFibroblastInsertFeatures100bp ../PWMData/HumanDownFibroblastDelFeatures100bp > ../PWMData/HumanDownFibroblastSeqDiffFUnsorted100bp
cat ../PWMData/HumanDownFibroblastSubFeaturesUp100bp ../PWMData/HumanDownFibroblastInsertFeaturesUp100bp ../PWMData/HumanDownFibroblastDelFeaturesUp100bp > ../PWMData/HumanDownFibroblastSeqDiffFUnsortedUp100bp
cat ../PWMData/HumanDownFibroblastSubFeaturesDown100bp ../PWMData/HumanDownFibroblastInsertFeaturesDown100bp ../PWMData/HumanDownFibroblastDelFeaturesDown100bp > ../PWMData/HumanDownFibroblastSeqDiffFUnsortedDown100bp
cat ../PWMData/HumanDownFibroblastSub100kbFeatures100bp ../PWMData/HumanDownFibroblastInsert100kbFeatures100bp ../PWMData/HumanDownFibroblastDel100kbFeatures100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFUnsorted100bp
cat ../PWMData/HumanDownFibroblastSub100kbFeaturesUp100bp ../PWMData/HumanDownFibroblastInsert100kbFeaturesUp100bp ../PWMData/HumanDownFibroblastDel100kbFeaturesUp100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFUnsortedUp100bp
cat ../PWMData/HumanDownFibroblastSub100kbFeaturesDown100bp ../PWMData/HumanDownFibroblastInsert100kbFeaturesDown100bp ../PWMData/HumanDownFibroblastDel100kbFeaturesDown100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFUnsortedDown100bp
paste ../DNaseRegionData/HumanDownFibroblastSeqDiffs100bp ../PWMData/HumanDownFibroblastSeqDiffFUnsorted100bp > ../PWMData/HumanDownFibroblastSeqDiffFULoc100bp
paste ../DNaseRegionData/HumanDownFibroblastSeqDiffs100bp ../PWMData/HumanDownFibroblastSeqDiffFUnsortedUp100bp > ../PWMData/HumanDownFibroblastSeqDiffFULocUp100bp
paste ../DNaseRegionData/HumanDownFibroblastSeqDiffs100bp ../PWMData/HumanDownFibroblastSeqDiffFUnsortedDown100bp > ../PWMData/HumanDownFibroblastSeqDiffFULocDown100bp
paste ../DNaseRegionData/HumanDownFibroblastSeqDiffs100bp ../PWMData/HumanDownFibroblastSeqDiff100kbFUnsorted100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFULoc100bp
paste ../DNaseRegionData/HumanDownFibroblastSeqDiffs100bp ../PWMData/HumanDownFibroblastSeqDiff100kbFUnsortedUp100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFULocUp100bp
paste ../DNaseRegionData/HumanDownFibroblastSeqDiffs100bp ../PWMData/HumanDownFibroblastSeqDiff100kbFUnsortedDown100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFULocDown100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanDownFibroblastSeqDiffFULoc100bp > ../PWMData/HumanDownFibroblastSeqDiffFSLoc100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanDownFibroblastSeqDiffFULocUp100bp > ../PWMData/HumanDownFibroblastSeqDiffFSLocUp100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanDownFibroblastSeqDiffFULocDown100bp > ../PWMData/HumanDownFibroblastSeqDiffFSLocDown100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanDownFibroblastSeqDiff100kbFULoc100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFSLoc100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanDownFibroblastSeqDiff100kbFULocUp100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFSLocUp100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/HumanDownFibroblastSeqDiff100kbFULocDown100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFSLocDown100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanDownFibroblastSeqDiffFSLoc100bp > ../PWMData/HumanDownFibroblastSeqDiffFSorted100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanDownFibroblastSeqDiffFSLocUp100bp > ../PWMData/HumanDownFibroblastSeqDiffFSortedUp100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanDownFibroblastSeqDiffFSLocDown100bp > ../PWMData/HumanDownFibroblastSeqDiffFSortedDown100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanDownFibroblastSeqDiff100kbFSLoc100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFSorted100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanDownFibroblastSeqDiff100kbFSLocUp100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFSortedUp100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/HumanDownFibroblastSeqDiff100kbFSLocDown100bp > ../PWMData/HumanDownFibroblastSeqDiff100kbFSortedDown100bp

intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadCtcfStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToCtcfReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K4me3ReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K27me3ReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K36me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K36me3ReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadEzh2StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToEzh2ReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me1StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K4me1ReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9acStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K9acReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K9me3ReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27acStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K27acReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K79me2StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K79me2ReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH4K20me1StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH4K20me1ReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH2azStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH2azReadNums
intersectBed -a ../DNaseRegionData/HumanDownFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me2StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K4me2ReadNums

python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadCtcfStdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToCtcfReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToCtcf 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me3StdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K4me3ReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH3K4me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27me3StdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K27me3ReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH3K27me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K36me3StdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K36me3ReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH3K36me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadEzh2StdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToEzh2ReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToEzh2 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me1StdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K4me1ReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH3K4me1 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9acStdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K9acReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH3K9ac 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9me3StdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K9me3ReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH3K9me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27acStdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K27acReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH3K27ac 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K79me2StdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K79me2ReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH3K79me2 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH4K20me1StdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH4K20me1ReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH4K20me1 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH2azStdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH2azReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH2az 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me2StdPk.Sorted.broadPeak ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/HumanDownFibroblastRegion100bpToH3K4me2ReadNums ../ENCODEData/NHDF_Ad/HumanDownFibroblastSeqDiffsToH3K4me2 3 3
python combineFeatureFiles.py ../DNaseRegionData/HumanDownFibroblastSeqDiffsSorted100bp ../FeatureData/HumanDownFibroblastFeatureFileNamesDown ../FeatureData/HumanDownFibroblastFeaturesDown100bp
python associateRegionsToClusters.py ../DNaseRegionData/HumanDownFibroblastMappanTro2rheMac2Sorted ../HumanGenome/HumanCoordsClustersFileNames ../DNaseRegionData/HumanDownFibroblastMapClusters 4
python associateSeqDiffsToClusters.py ../DNaseRegionData/HumanDownFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/HumanDownFibroblastMapClusters ../DNaseRegionData/HumanDownFibroblastSeqDiffsClusters100bp


python filterPeakWindowsLineNums.py ../DNasePeaks/allPeaksWindowsO15D282M652FiltLCL ../DNasePeaks/CommonFibroblastLines ../DNaseRegionData/CommonFibroblast 0
./liftOver -minMatch=0.8 ../DNaseRegionData/CommonFibroblast ../LiftoverChains/hg19ToPanTro2.over.chain ../DNaseRegionData/CommonFibroblastpanTro2 ../DNaseRegionData/CommonFibroblastUnmapped
subtractBed -a ../DNaseRegionData/CommonFibroblast -b ../DNaseRegionData/CommonFibroblastUnmapped > ../DNaseRegionData/CommonFibroblastMappanTro2
./liftOver -minMatch=0.8 ../DNaseRegionData/CommonFibroblast ../LiftoverChains/hg19ToRheMac2.over.chain ../DNaseRegionData/CommonFibroblastrheMac2 ../DNaseRegionData/CommonFibroblastUnmappedrheMac2
subtractBed -a ../DNaseRegionData/CommonFibroblastMappanTro2 -b ../DNaseRegionData/CommonFibroblastUnmappedrheMac2 > ../DNaseRegionData/CommonFibroblastMappanTro2rheMac2
sort -u -k1,1 -k2,2n -k3,3n ../DNaseRegionData/CommonFibroblastMappanTro2rheMac2 > ../DNaseRegionData/CommonFibroblastMappanTro2rheMac2Sorted
python getRegionsOfInterest.py ../DNaseRegionData/CommonFibroblastMappanTro2rheMac2Sorted 0 1 2 100 1 0 0 1 0 0 ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../AlignmentFiles/all.hg19.panTro2.rheMac2.substitutions > ../DNaseRegionData/CommonFibroblastSubstitutionsCommon100bp
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../AlignmentFiles/all.hg19.panTro2.rheMac2.insertions > ../DNaseRegionData/CommonFibroblastInsertions100bp
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../AlignmentFiles/all.hg19.panTro2.rheMac2.deletions > ../DNaseRegionData/CommonFibroblastDeletions100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp ../DNaseRegionData/CommonFibroblastSubstitutionsCommon100bp ../DNaseRegionData/CommonFibroblastRegionsToSubstitutions100bp -1 0 1 2 ../DNaseRegionData/CommonFibroblastSubstitutionsSingle100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp ../DNaseRegionData/CommonFibroblastInsertions100bp ../DNaseRegionData/CommonFibroblastRegionsToInsertions100bp -1 0 1 2 ../DNaseRegionData/CommonFibroblastInsertionsSingle100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp ../DNaseRegionData/CommonFibroblastDeletions100bp ../DNaseRegionData/CommonFibroblastRegionsToDeletions100bp -1 0 1 2 ../DNaseRegionData/CommonFibroblastDeletionsSingle100bp
cat ../DNaseRegionData/CommonFibroblastSubstitutionsCommon100bp ../DNaseRegionData/CommonFibroblastInsertions100bp ../DNaseRegionData/CommonFibroblastDeletions100bp > ../DNaseRegionData/CommonFibroblastSeqDiffs100bp
sort -k1,1 -k2,2n -k3,3n ../DNaseRegionData/CommonFibroblastSeqDiffs100bp > ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp
python associateRegionsToSequencesUCSCSingle.py ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp -1 0 1 2 ../DNaseRegionData/CommonFibroblastSeqDiffsSingle100bp
python addNamesToBed.py ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp ../DNaseRegionData/CommonFibroblastMapRegionSorted4Col100bp

python getRegionsOfInterest.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp 0 1 2 10 1 0 0 1 0 0 ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsSortedRegion10bp
python getRegionsOfInterest.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp 0 1 2 100 1 0 0 1 0 0 ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsSortedRegion100bp
python getRegionsOfInterest.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp 0 1 2 1000 1 0 0 1 0 0 ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsSortedRegion1000bp
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservP ../DNaseRegionData/CommonFibroblastMapConservP100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservPNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservP10bp ../DNaseRegionData/CommonFibroblastMapConservP100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservP10bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservP100bp ../DNaseRegionData/CommonFibroblastMapConservP100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservP100bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservP1000bp ../DNaseRegionData/CommonFibroblastMapConservP100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservP1000bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservM ../DNaseRegionData/CommonFibroblastMapConservM100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservMNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservM10bp ../DNaseRegionData/CommonFibroblastMapConservM100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservM10bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservM100bp ../DNaseRegionData/CommonFibroblastMapConservM100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservM100bpNorm
python getConservationNormFeatures.py ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservM1000bp ../DNaseRegionData/CommonFibroblastMapConservM100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/SeqDiffRegions100bp/CommonFibroblastSeqDiffsConservM1000bpNorm

python getDistancesFeaturesNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp 100 ../DNaseRegionData/SeqDiffDistances100bp/CommonFibroblastDistFeatsNorm

python getRegionsOfInterest.py ../DNaseRegionData/CommonFibroblastMappanTro2rheMac2Sorted 0 1 2 100000 1 0 0 1 0 0 ../DNaseRegionData/CommonFibroblastMapRegionSorted100kb
python addNamesToBed.py ../DNaseRegionData/CommonFibroblastMapRegionSorted100kb ../DNaseRegionData/CommonFibroblastMapRegionSorted4Col100kb
python getSubstitutionFastasAllSubs.py ../AlignmentFiles/all.hg19.panTro2.rheMac2.substitutions ../DNaseRegionData/CommonFibroblastSubstitutionsCommon100bp ../DNaseRegionData/CommonFibroblastSubstitutionsToSequences100bp
python substituteFastas.py ../DNaseRegionData/CommonFibroblastSubstitutionsToSequences100bp ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastMapFastasSorted100bp ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastFastasSubstitutionsSub100bp
python removeInsertions.py ../DNaseRegionData/CommonFibroblastInsertions100bp ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastMapFastasSorted100bp ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastFastasInsertionsRemoved100bp
python getSubstitutionFastasAllSubs.py ../AlignmentFiles/all.hg19.panTro2.rheMac2.deletions ../DNaseRegionData/CommonFibroblastDeletions100bp ../DNaseRegionData/CommonFibroblastDeletionsToSequences100bp
python addDeletions.py ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastMapFastasSorted100bp ../DNaseRegionData/CommonFibroblastDeletionsToSequences100bp ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastFastasDeletionsAdded100bp

python makeFIMOScript.py ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastMapFastasSorted100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/CommonFDR1GCContent100kb runFIMOCommonFibroblast100kb.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundCommonFibroblast/FIMOCommonFibroblast100kb /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All
python makeFIMOScriptSub.py ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastFastasSubstitutionsSub100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/CommonFDR1GCContent100kb runFIMOCommonFibroblast100kbS.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundCommonFibroblastSub/FIMOCommonFibroblast100kbSub /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp
python makeFIMOScriptSub.py ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastFastasInsertionsRemoved100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/CommonFDR1GCContent100kb runFIMOCommonFibroblast100kbI.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundCommonFibroblastIns/FIMOCommonFibroblast100kbIns /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp
python makeFIMOScriptSub.py ../DNaseRegionData/DNaseFastas100bp/CommonFibroblastFastasDeletionsAdded100bp /science/irene/PrimateSNPProject/DNaseRegionData/DNaseFastas100bp/ /science/irene/PrimateSNPProject/GCContentInfo/CommonFDR1GCContent100kb runFIMOCommonFibroblast100kbD.sh /science/irene/PrimateSNPProject/PWMData/FIMO100kbBackgroundCommonFibroblastDel/FIMOCommonFibroblast100kbDel /science/irene/PrimateSNPProject/PWMData/CisBP_2013_02_25/PWMMEME_All ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp

cat ../PWMData/CommonFibroblastSubFeatures100bp ../PWMData/CommonFibroblastInsertFeatures100bp ../PWMData/CommonFibroblastDelFeatures100bp > ../PWMData/CommonFibroblastSeqDiffFUnsorted100bp
cat ../PWMData/CommonFibroblastSubFeaturesUp100bp ../PWMData/CommonFibroblastInsertFeaturesUp100bp ../PWMData/CommonFibroblastDelFeaturesUp100bp > ../PWMData/CommonFibroblastSeqDiffFUnsortedUp100bp
cat ../PWMData/CommonFibroblastSubFeaturesDown100bp ../PWMData/CommonFibroblastInsertFeaturesDown100bp ../PWMData/CommonFibroblastDelFeaturesDown100bp > ../PWMData/CommonFibroblastSeqDiffFUnsortedDown100bp
cat ../PWMData/CommonFibroblastSub100kbFeatures100bp ../PWMData/CommonFibroblastInsert100kbFeatures100bp ../PWMData/CommonFibroblastDel100kbFeatures100bp > ../PWMData/CommonFibroblastSeqDiff100kbFUnsorted100bp
cat ../PWMData/CommonFibroblastSub100kbFeaturesUp100bp ../PWMData/CommonFibroblastInsert100kbFeaturesUp100bp ../PWMData/CommonFibroblastDel100kbFeaturesUp100bp > ../PWMData/CommonFibroblastSeqDiff100kbFUnsortedUp100bp
cat ../PWMData/CommonFibroblastSub100kbFeaturesDown100bp ../PWMData/CommonFibroblastInsert100kbFeaturesDown100bp ../PWMData/CommonFibroblastDel100kbFeaturesDown100bp > ../PWMData/CommonFibroblastSeqDiff100kbFUnsortedDown100bp
paste ../DNaseRegionData/CommonFibroblastSeqDiffs100bp ../PWMData/CommonFibroblastSeqDiffFUnsorted100bp > ../PWMData/CommonFibroblastSeqDiffFULoc100bp
paste ../DNaseRegionData/CommonFibroblastSeqDiffs100bp ../PWMData/CommonFibroblastSeqDiffFUnsortedUp100bp > ../PWMData/CommonFibroblastSeqDiffFULocUp100bp
paste ../DNaseRegionData/CommonFibroblastSeqDiffs100bp ../PWMData/CommonFibroblastSeqDiffFUnsortedDown100bp > ../PWMData/CommonFibroblastSeqDiffFULocDown100bp
paste ../DNaseRegionData/CommonFibroblastSeqDiffs100bp ../PWMData/CommonFibroblastSeqDiff100kbFUnsorted100bp > ../PWMData/CommonFibroblastSeqDiff100kbFULoc100bp
paste ../DNaseRegionData/CommonFibroblastSeqDiffs100bp ../PWMData/CommonFibroblastSeqDiff100kbFUnsortedUp100bp > ../PWMData/CommonFibroblastSeqDiff100kbFULocUp100bp
paste ../DNaseRegionData/CommonFibroblastSeqDiffs100bp ../PWMData/CommonFibroblastSeqDiff100kbFUnsortedDown100bp > ../PWMData/CommonFibroblastSeqDiff100kbFULocDown100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/CommonFibroblastSeqDiffFULoc100bp > ../PWMData/CommonFibroblastSeqDiffFSLoc100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/CommonFibroblastSeqDiffFULocUp100bp > ../PWMData/CommonFibroblastSeqDiffFSLocUp100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/CommonFibroblastSeqDiffFULocDown100bp > ../PWMData/CommonFibroblastSeqDiffFSLocDown100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/CommonFibroblastSeqDiff100kbFULoc100bp > ../PWMData/CommonFibroblastSeqDiff100kbFSLoc100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/CommonFibroblastSeqDiff100kbFULocUp100bp > ../PWMData/CommonFibroblastSeqDiff100kbFSLocUp100bp
sort -k1,1 -k2,2n -k3,3n ../PWMData/CommonFibroblastSeqDiff100kbFULocDown100bp > ../PWMData/CommonFibroblastSeqDiff100kbFSLocDown100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/CommonFibroblastSeqDiffFSLoc100bp > ../PWMData/CommonFibroblastSeqDiffFSorted100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/CommonFibroblastSeqDiffFSLocUp100bp > ../PWMData/CommonFibroblastSeqDiffFSortedUp100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/CommonFibroblastSeqDiffFSLocDown100bp > ../PWMData/CommonFibroblastSeqDiffFSortedDown100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/CommonFibroblastSeqDiff100kbFSLoc100bp > ../PWMData/CommonFibroblastSeqDiff100kbFSorted100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/CommonFibroblastSeqDiff100kbFSLocUp100bp > ../PWMData/CommonFibroblastSeqDiff100kbFSortedUp100bp
cut -f4,5,6,7,8,9,10,11 ../PWMData/CommonFibroblastSeqDiff100kbFSLocDown100bp > ../PWMData/CommonFibroblastSeqDiff100kbFSortedDown100bp

intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadCtcfStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToCtcfReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K4me3ReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K27me3ReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K36me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K36me3ReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadEzh2StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToEzh2ReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me1StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K4me1ReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9acStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K9acReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9me3StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K9me3ReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27acStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K27acReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K79me2StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K79me2ReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH4K20me1StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH4K20me1ReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH2azStdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH2azReadNums
intersectBed -a ../DNaseRegionData/CommonFibroblastMapRegionSorted100bp -b ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me2StdAlnReadsPooled.bed -c > ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K4me2ReadNums

python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadCtcfStdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToCtcfReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToCtcf 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me3StdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K4me3ReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH3K4me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27me3StdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K27me3ReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH3K27me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K36me3StdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K36me3ReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH3K36me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadEzh2StdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToEzh2ReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToEzh2 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me1StdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K4me1ReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH3K4me1 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9acStdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K9acReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH3K9ac 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K9me3StdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K9me3ReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH3K9me3 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K27acStdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K27acReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH3K27ac 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K79me2StdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K79me2ReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH3K79me2 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH4K20me1StdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH4K20me1ReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH4K20me1 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH2azStdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH2azReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH2az 3 3
python associateSeqDiffsToPeaksNorm.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../ENCODEData/NHDF_Ad/wgEncodeBroadHistoneNhdfadH3K4me2StdPk.Sorted.broadPeak ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../ENCODEData/NHDF_Ad/CommonFibroblastRegion100bpToH3K4me2ReadNums ../ENCODEData/NHDF_Ad/CommonFibroblastSeqDiffsToH3K4me2 3 3
python combineFeatureFiles.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../FeatureData/CommonFibroblastFeatureFileNamesUp ../FeatureData/CommonFibroblastFeaturesUp100bp
python combineFeatureFiles.py ../DNaseRegionData/CommonFibroblastSeqDiffsSorted100bp ../FeatureData/CommonFibroblastFeatureFileNamesDown ../FeatureData/CommonFibroblastFeaturesDown100bp
python associateRegionsToClusters.py ../DNaseRegionData/CommonFibroblastMappanTro2rheMac2Sorted ../HumanGenome/HumanCoordsClustersFileNames ../DNaseRegionData/CommonFibroblastMapClusters 4
python associateSeqDiffsToClusters.py ../DNaseRegionData/CommonFibroblastRegionsToSeqDiffs100bp ../DNaseRegionData/CommonFibroblastMapClusters ../DNaseRegionData/CommonFibroblastSeqDiffsClusters100bp
