python getConservation.py ../DNaseRegionData/Indels200bp/HumanDownFibroblastInsertionsSorted ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertionsConservP
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertions20bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertionsConservP20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertions200bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertionsConservP200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertions2000bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertionsConservP2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/HumanDownFibroblastDeletionsSorted ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletionsConservP
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletions20bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletionsConservP20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletions200bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletionsConservP200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletions2000bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletionsConservP2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/HumanUpFibroblastInsertionsSorted ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertionsConservP
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertions20bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertionsConservP20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertions200bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertionsConservP200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertions2000bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertionsConservP2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/HumanUpFibroblastDeletionsSorted ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletionsConservP
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletions20bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletionsConservP20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletions200bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletionsConservP200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletions2000bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletionsConservP2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/commonHumanFibroblastInsertionsSorted ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertionsConservP
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertions20bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertionsConservP20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertions200bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertionsConservP200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertions2000bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertionsConservP2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/commonHumanFibroblastDeletionsSorted ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletionsConservP
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletions20bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletionsConservP20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletions200bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletionsConservP200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletions2000bp ../ConservationData/Primates/chrAll.phastCons46way.primates.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletionsConservP2000bp
