python getConservation.py ../DNaseRegionData/Indels200bp/HumanDownFibroblastInsertionsSorted ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertionsConserv
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertions20bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertionsConserv20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertions200bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertionsConserv200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertions2000bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastInsertionsConserv2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/HumanDownFibroblastDeletionsSorted ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletionsConserv
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletions20bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletionsConserv20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletions200bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletionsConserv200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletions2000bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanDownFibroblastDeletionsConserv2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/HumanUpFibroblastInsertionsSorted ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertionsConserv
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertions20bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertionsConserv20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertions200bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertionsConserv200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertions2000bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastInsertionsConserv2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/HumanUpFibroblastDeletionsSorted ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletionsConserv
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletions20bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletionsConserv20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletions200bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletionsConserv200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletions2000bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/HumanUpFibroblastDeletionsConserv2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/commonHumanFibroblastInsertionsSorted ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertionsConserv
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertions20bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertionsConserv20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertions200bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertionsConserv200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertions2000bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastInsertionsConserv2000bp

python getConservation.py ../DNaseRegionData/Indels200bp/commonHumanFibroblastDeletionsSorted ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletionsConserv
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletions20bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletionsConserv20bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletions200bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletionsConserv200bp
python getConservation.py ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletions2000bp ../ConservationData/Mammals/chrAll.phastCons46way.placental.wigFix ../DNaseRegionData/Indels200bp/IndelRegions/commonHumanFibroblastDeletionsConserv2000bp
