python getPWMFeaturesTFSpecific.py ../PWMData/FIMOHumanDDFibroblast100bp/fimo.txt ../PWMData/FIMOHumanDDFibroblast100bpSub/fimo.txt ../DNaseRegionData/HumanDDFibroblastSubstitutionsCommon100bp ../DNaseRegionData/HumanDDFibroblastRegionsToSubstitutions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/HumanDDFibroblastSubFeatures100bp ../PWMData/HumanDDFibroblastSubFeaturesUp100bp ../PWMData/HumanDDFibroblastSubFeaturesDown100bp
python getPWMFeaturesTFSpecific.py ../PWMData/FIMOCommonFibroblast100bp/fimo.txt ../PWMData/FIMOCommonFibroblast100bpSub/fimo.txt ../DNaseRegionData/CommonFibroblastSubstitutionsCommon100bp ../DNaseRegionData/CommonFibroblastRegionsToSubstitutions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/CommonFibroblastSubFeatures100bp ../PWMData/CommonFibroblastSubFeaturesUp100bp ../PWMData/CommonFibroblastSubFeaturesDown100bp

python getPWMFeaturesTFSpecific.py ../PWMData/FIMO100kbBackgroundHumanDDFibroblast/fimoCat ../PWMData/FIMO100kbBackgroundHumanDDFibroblastSub/fimoSubCat ../DNaseRegionData/HumanDDFibroblastSubstitutionsCommon100bp ../DNaseRegionData/HumanDDFibroblastRegionsToSubstitutions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/HumanDDFibroblastSub100kbFeatures100bp ../PWMData/HumanDDFibroblastSub100kbFeaturesUp100bp ../PWMData/HumanDDFibroblastSub100kbFeaturesDown100bp
python getPWMFeaturesTFSpecific.py ../PWMData/FIMO100kbBackgroundCommonFibroblast/fimoCat ../PWMData/FIMO100kbBackgroundCommonFibroblastSub/fimoSubCat ../DNaseRegionData/CommonFibroblastSubstitutionsCommon100bp ../DNaseRegionData/CommonFibroblastRegionsToSubstitutions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/CommonFibroblastSub100kbFeatures100bp ../PWMData/CommonFibroblastSub100kbFeaturesUp100bp ../PWMData/CommonFibroblastSub100kbFeaturesDown100bp

python getPWMFeaturesTFSpecific.py ../PWMData/FIMOHumanDDFibroblast100bp/fimo.txt ../PWMData/FIMOHumanDDFibroblast100bpIns/fimo.txt ../DNaseRegionData/HumanDDFibroblastInsertions100bp ../DNaseRegionData/HumanDDFibroblastRegionsToInsertions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/HumanDDFibroblastInsertFeatures100bp ../PWMData/HumanDDFibroblastInsertFeaturesUp100bp ../PWMData/HumanDDFibroblastInsertFeaturesDown100bp
python getPWMFeaturesTFSpecific.py ../PWMData/FIMOCommonFibroblast100bp/fimo.txt ../PWMData/FIMOCommonFibroblast100bpIns/fimo.txt ../DNaseRegionData/CommonFibroblastInsertions100bp ../DNaseRegionData/CommonFibroblastRegionsToInsertions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/CommonFibroblastInsertFeatures100bp ../PWMData/CommonFibroblastInsertFeaturesUp100bp ../PWMData/CommonFibroblastInsertFeaturesDown100bp

python getPWMFeaturesTFSpecific.py ../PWMData/FIMO100kbBackgroundHumanDDFibroblast/fimoCat ../PWMData/FIMO100kbBackgroundHumanDDFibroblastIns/fimoInsCat ../DNaseRegionData/HumanDDFibroblastInsertions100bp ../DNaseRegionData/HumanDDFibroblastRegionsToInsertions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/HumanDDFibroblastInsert100kbFeatures100bp ../PWMData/HumanDDFibroblastInsert100kbFeaturesUp100bp ../PWMData/HumanDDFibroblastInsert100kbFeaturesDown100bp
python getPWMFeaturesTFSpecific.py ../PWMData/FIMO100kbBackgroundCommonFibroblast/fimoCat ../PWMData/FIMO100kbBackgroundCommonFibroblastIns/fimoInsCat ../DNaseRegionData/CommonFibroblastInsertions100bp ../DNaseRegionData/CommonFibroblastRegionsToInsertions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/CommonFibroblastInsert100kbFeatures100bp ../PWMData/CommonFibroblastInsert100kbFeaturesUp100bp ../PWMData/CommonFibroblastInsert100kbFeaturesDown100bp

python getPWMFeaturesTFSpecific.py ../PWMData/FIMOHumanDDFibroblast100bp/fimo.txt ../PWMData/FIMOHumanDDFibroblast100bpDel/fimo.txt ../DNaseRegionData/HumanDDFibroblastDeletions100bp ../DNaseRegionData/HumanDDFibroblastRegionsToDeletions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/HumanDDFibroblastDelFeatures100bp ../PWMData/HumanDDFibroblastDelFeaturesUp100bp ../PWMData/HumanDDFibroblastDelFeaturesDown100bp
python getPWMFeaturesTFSpecific.py ../PWMData/FIMOCommonFibroblast100bp/fimo.txt ../PWMData/FIMOCommonFibroblast100bpDel/fimo.txt ../DNaseRegionData/CommonFibroblastDeletions100bp ../DNaseRegionData/CommonFibroblastRegionsToDeletions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/CommonFibroblastDelFeatures100bp ../PWMData/CommonFibroblastDelFeaturesUp100bp ../PWMData/CommonFibroblastDelFeaturesDown100bp

python getPWMFeaturesTFSpecific.py ../PWMData/FIMO100kbBackgroundHumanDDFibroblast/fimoCat ../PWMData/FIMO100kbBackgroundHumanDDFibroblastDel/fimoDelCat ../DNaseRegionData/HumanDDFibroblastDeletions100bp ../DNaseRegionData/HumanDDFibroblastRegionsToDeletions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/HumanDDFibroblastDel100kbFeatures100bp ../PWMData/HumanDDFibroblastDel100kbFeaturesUp100bp ../PWMData/HumanDDFibroblastDel100kbFeaturesDown100bp
python getPWMFeaturesTFSpecific.py ../PWMData/FIMO100kbBackgroundCommonFibroblast/fimoCat ../PWMData/FIMO100kbBackgroundCommonFibroblastDel/fimoDelCat ../DNaseRegionData/CommonFibroblastDeletions100bp ../DNaseRegionData/CommonFibroblastRegionsToDeletions100bp ../PWMData/FIMOFibroblast100bpTFs ../PWMData/CommonFibroblastDel100kbFeatures100bp ../PWMData/CommonFibroblastDel100kbFeaturesUp100bp ../PWMData/CommonFibroblastDel100kbFeaturesDown100bp
