maf_div_sites_threeway.py ../AlignmentFiles/chr1.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr1.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr10.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr10.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr11.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr11.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr12.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr12.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr13.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr13.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr14.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr14.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr15.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr15.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr16.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr16.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr17.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr17.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr18.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr18.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr19.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr19.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr2.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr2.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr20.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr20.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr21.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr21.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr22.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr22.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr3.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr3.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr4.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr4.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr5.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr5.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr6.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr6.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr7.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr7.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr8.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr8.hg19.panTro2.rheMac2.substitutions
maf_div_sites_threeway.py ../AlignmentFiles/chr9.hg19.panTro2.rheMac2.maf hg19 panTro2 rheMac2 > ../AlignmentFiles/chr9.hg19.panTro2.rheMac2.substitutions

cat ../AlignmentFiles/chr1.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr10.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr11.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr12.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr13.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr14.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr15.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr16.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr17.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr18.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr19.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr2.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr20.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr21.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr22.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr3.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr4.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr5.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr6.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr7.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr8.hg19.panTro2.rheMac2.substitutions ../AlignmentFiles/chr9.hg19.panTro2.rheMac2.substitutions | sort -u -k1,1 -k2,2n -k3,3n > ../AlignmentFiles/all.hg19.panTro2.rheMac2.substitutions
