library("snow")
library("baySeq")
cl <- makeCluster(8, "SOCK")
data = matrix(scan("/science/irene/PrimateSNPProject/DNasePeaks/HCMFibroblastAllReadsWindowSCFilt"),ncol=9,byrow=TRUE)
replicates <- c("Human", "Human", "Human", "Chimp", "Chimp", "Chimp", "Macaque", "Macaque", "Macaque")
groups <- list(NDE = c(1,1,1,1,1,1,1,1,1), DEHuman = c(1,1,1,2,2,2,2,2,2), DEChimp = c(2,2,2,1,1,1,2,2,2), DEMacaque = c(2,2,2,2,2,2,1,1,1), DEAll = c(1,1,1,2,2,2,3,3,3))
CD <- new("countData", data = data, replicates = replicates, groups = groups)
libsizes <- getLibsizes(CD)
CD <- getPriors.NB(CD, samplesize=131509, estimation = "QL", cl = cl)
CD <- getLikelihoods.NB(CD, pET='BIC', cl = cl)
save(CD, file = "/science/irene/PrimateSNPProject/DNasePeaks/baySeqOutFibroblast.RData")
write(CD@posteriors, file = "/science/irene/PrimateSNPProject/DNasePeaks/baySeqOutFibroblastPosteriors.txt")
topCountsNDE <- topCounts(CD, group = "NDE", FDR=0.05)
write.csv(topCountsNDE, file="/science/irene/PrimateSNPProject/DNasePeaks/baySeqOutFibroblastNDE.csv")
topCountsDEHuman <- topCounts(CD, group = "DEHuman", FDR=0.05)
write.csv(topCountsDEHuman, file="/science/irene/PrimateSNPProject/DNasePeaks/baySeqOutFibroblastDEHuman.csv")
topCountsDEChimp <- topCounts(CD, group = "DEChimp", FDR=0.05)
write.csv(topCountsDEChimp, file="/science/irene/PrimateSNPProject/DNasePeaks/baySeqOutFibroblastDEChimp.csv")
topCountsDEMacaque <- topCounts(CD, group = "DEMacaque", FDR=0.05)
write.csv(topCountsDEMacaque, file="/science/irene/PrimateSNPProject/DNasePeaks/baySeqOutFibroblastDEMacaque.csv")
topCountsDEAll <- topCounts(CD, group = "DEAll", FDR=0.05)
write.csv(topCountsDEAll, file="/science/irene/PrimateSNPProject/DNasePeaks/baySeqOutFibroblastDEAll.csv")
